export type NewsItem = {
  id: string;
  date: string; // ISO date
  source: string;
  sourceType: 'press' | 'movement' | 'drop' | 'social';
  title: string;
  blurb: string;
  url: string;
  external?: boolean;
};

export const NEWS_ITEMS: NewsItem[] = [
  // === International press ===
  {
    id: 'cnn-viral',
    date: '2026-05-21',
    source: 'CNN',
    sourceType: 'press',
    title: "India's 'cockroach' party goes viral",
    blurb: 'CNN covers how a satirical political party born from a Chief Justice\'s offhand comment is overtaking the ruling BJP on Instagram in days.',
    url: 'https://edition.cnn.com/2026/05/21/world/video/india-chief-justice-cockroach-janta-party-mogul-vrtc',
    external: true,
  },
  {
    id: 'wapo-youth-anger',
    date: '2026-05-21',
    source: 'The Washington Post',
    sourceType: 'press',
    title: "A parody 'cockroach' party in India becomes major outlet for youth anger and protest",
    blurb: 'The Washington Post on how the CJP movement is channelling Gen Z frustration over unemployment, inflation, and political dysfunction.',
    url: 'https://www.washingtonpost.com/business/2026/05/21/india-cockroach-janta-party/8c066a10-5514-11f1-9c40-7a0a12d9e745_story.html',
    external: true,
  },
  {
    id: 'aljazeera-cji',
    date: '2026-05-20',
    source: 'Al Jazeera',
    sourceType: 'press',
    title: "Cockroach Janta Party: Top Indian judge's comment sparks satire, protest",
    blurb: "Al Jazeera traces the movement back to Chief Justice Surya Kant's 'cockroaches' remark — and the meme storm that followed.",
    url: 'https://www.aljazeera.com/features/2026/5/20/cockroach-janata-party-top-indian-judges-comment-sparks-satire-protest',
    external: true,
  },
  {
    id: 'dna-trademark',
    date: '2026-05-21',
    source: 'DNA India',
    sourceType: 'press',
    title: "Who is the real 'cockroach'? CJP moves beyond memes as 3 trademark filings surface",
    blurb: 'Three separate trademark applications have been filed for the phrase "Cockroach Janta Party". The race for ownership has begun.',
    url: 'https://www.dnaindia.com/india/report-who-is-the-real-cockroach-cockroach-janta-party-moves-beyond-memes-as-3-trademark-filings-surface-3211126',
    external: true,
  },
  {
    id: 'theprint-founder',
    date: '2026-05-21',
    source: 'The Print',
    sourceType: 'press',
    title: 'CJP Dalit founder Abhijeet Dipke faces caste attacks on X',
    blurb: 'The Print on the targeted attacks against founder Abhijeet Dipke and the ugly side of going viral in Indian internet politics.',
    url: 'https://theprint.in/feature/cockroach-janta-party-dalit-abhijeet-dipke-caste-attacks/2937920/',
    external: true,
  },
  {
    id: 'sundayguardian-founder',
    date: '2026-05-21',
    source: 'Sunday Guardian',
    sourceType: 'press',
    title: 'Who is Abhijeet Dipke? The 30-year-old Boston University student behind CJP',
    blurb: 'A full profile of the political communications strategist who founded CJP on May 16 — caste, qualifications, and links explored.',
    url: 'https://sundayguardianlive.com/trending/who-is-abhijeet-dipke-check-cockroach-janata-party-founders-caste-qualification-age-link-with-aap-linkedin-instagram-x-account-and-more-195055/',
    external: true,
  },
  {
    id: 'wikipedia',
    date: '2026-05-20',
    source: 'Wikipedia',
    sourceType: 'press',
    title: 'Cockroach Janta Party — Wikipedia article goes live',
    blurb: 'The movement officially crosses the threshold into encyclopaedic record. Read the live, evolving entry.',
    url: 'https://en.wikipedia.org/wiki/Cockroach_Janta_Party',
    external: true,
  },

  // === Movement milestones ===
  {
    id: 'milestone-15m',
    date: '2026-05-21',
    source: 'CJP Tracker',
    sourceType: 'movement',
    title: 'CJP crosses 15 million Instagram followers — overtakes BJP',
    blurb: 'In under a week, the parody account has surpassed the ruling Bharatiya Janata Party\'s 8.8M followers. Place your bet on Sunday\'s number.',
    url: '/predict',
  },
  {
    id: 'milestone-10m',
    date: '2026-05-20',
    source: 'CJP Tracker',
    sourceType: 'movement',
    title: '10 million followers in 5 days',
    blurb: 'After hitting 3M in 78 hours, the swarm doubled-and-then-some. The Indian internet has spoken.',
    url: 'https://www.instagram.com/cockroachjantaparty/',
    external: true,
  },
  {
    id: 'milestone-3m',
    date: '2026-05-18',
    source: 'CJP Tracker',
    sourceType: 'movement',
    title: '3 million followers in 78 hours',
    blurb: 'The first major milestone. A satirical movement turns into actual political signal.',
    url: 'https://www.instagram.com/cockroachjantaparty/',
    external: true,
  },
  {
    id: 'founding',
    date: '2026-05-16',
    source: 'The Founding',
    sourceType: 'movement',
    title: 'Cockroach Janta Party founded',
    blurb: 'Abhijeet Dipke launches CJP as a satirical response to CJI Surya Kant\'s "cockroaches" remark in an open court hearing.',
    url: 'https://cockroachjantaparty.org/',
    external: true,
  },
  {
    id: 'the-quote',
    date: '2026-05-15',
    source: 'The Spark',
    sourceType: 'movement',
    title: 'The quote that started it all',
    blurb: '"There are youngsters like cockroaches, who don\'t get any employment or have any place in the profession…" — CJI Surya Kant, in open court.',
    url: 'https://www.aljazeera.com/features/2026/5/20/cockroach-janata-party-top-indian-judges-comment-sparks-satire-protest',
    external: true,
  },

  // === CJP Drip drops ===
  {
    id: 'drop-stickers',
    date: '2026-05-22',
    source: 'CJP Drip',
    sourceType: 'drop',
    title: 'Sticker drop announced — Drop No. 002',
    blurb: 'Five vinyl sticker designs, kiss-cut, waterproof. From ₹79. The first sticker drop is now live for pre-order.',
    url: '/stickers',
  },
  {
    id: 'drop-mugs',
    date: '2026-05-21',
    source: 'CJP Drip',
    sourceType: 'drop',
    title: 'Mug drop — five ceramic mugs join the catalogue',
    blurb: 'For the chai before the interview. Five mug designs from the tee collection, ₹349 each.',
    url: '/',
  },
  {
    id: 'drop-001',
    date: '2026-05-21',
    source: 'CJP Drip',
    sourceType: 'drop',
    title: 'Drop No. 001 live — 19 tees, the founding collection',
    blurb: 'The Black Protest Tee, the Manifesto, the Parasite, the Cockroach in Chief — the first 19 designs are live.',
    url: '/',
  },
    {
    id: "cockroach-janta-party-cjp-how-abhijeet-dipke-s-collective-be",
    date: "2026-05-21",
    source: "BBC",
    sourceType: 'press',
    title: "Cockroach Janta Party (CJP): How Abhijeet Dipke's collective became an online sensation - BBC",
    blurb: "Read the full story on BBC.",
    url: "https://news.google.com/rss/articles/CBMiWkFVX3lxTE9Lc0Q0bU44S1NCUEdodXF2enMwVDlsLUlrV08tTFJ1TUppNGFWNlhFV1VtQlpMRndaNEo4TXdJRUsza0lGYjRLcmJhZkswbTlxRjBUbW9MZy0tZw?oc=5",
    external: true,
  },
  {
    id: "india-s-cockroach-group-goes-viral-spotlights-gen-z-worries-",
    date: "2026-05-21",
    source: "Reuters",
    sourceType: 'press',
    title: "India's 'Cockroach' group goes viral, spotlights Gen Z worries - Reuters",
    blurb: "Read the full story on Reuters.",
    url: "https://news.google.com/rss/articles/CBMiqgFBVV95cUxQZlFQbmZWWWhCWXVWQUNhUDdXaGw5Rmc3cE5lRVN4Rm91dkt5OER2YzV0TFBEVm5Mc0V0RHc4azQxRVc1S3FiUzRJNHJ5bnpqMl8xMV9PQU5Zb3N3WHlFYUYyVDg5TDQtdFN3VHg1ZFI0OUo3YU54UGo0NU9kdWMyaTJUM0RLaGRtTXozODZhbXBzX0Q4U2psSC16RVdacXV2elBJTmZKYndHQQ?oc=5",
    external: true,
  },
  {
    id: "india-news-cockroaches-overtake-modi-s-bjp-on-instagram-dw-c",
    date: "2026-05-21",
    source: "DW.com",
    sourceType: 'press',
    title: "India news: Cockroaches overtake Modi's BJP on Instagram - DW.com",
    blurb: "Read the full story on DW.com.",
    url: "https://news.google.com/rss/articles/CBMilAFBVV95cUxORDFhdmNNRmxFVHY2T3BZY2FDeEpRT2RoT2FUVGJGQ2thNnBuNVFnVnFTOVA1dWFhbEVoNEYxRmVYb2pUX2tfVFVpUVRZZUJEUXJIVXl1MlVrY3podXdYMWp0S09UamdzMkx0VGs5anBGUG9kVnBISk0xQk9pTl9abTdSSEZYdTVfT3FkRjBnVF84VU1l?oc=5",
    external: true,
  },
  {
    id: "cockroach-janata-party-s-x-handle-withheld-founder-starts-ne",
    date: "2026-05-21",
    source: "The Hindu",
    sourceType: 'press',
    title: "Cockroach Janata Party’s X handle withheld, founder starts new account - The Hindu",
    blurb: "Read the full story on The Hindu.",
    url: "https://news.google.com/rss/articles/CBMixgFBVV95cUxOREdHcEFlY2syQktYd1FjdUdqVVVkcmFTTHo4eFVYdjFPY3ZiQktlTWQ5cUVWNEw1SDR4TGpYa1RydURJWUlyRUdpZE42N2JMZ3c4QzN4dFAxN1NQbHN1TzZEdm1obXp1aUNDZm5yX0gtS29mN1dVZ044RFVzeW5ZYjNPczhmYkx5UE1mMTFQY3JzcjdTbnByS1hkVXBVOWJnSDczcTBFQnVlM2JBT1ZhYVF5QlJhSzBvYnExUjlvaHl0MXhhdGfSAcwBQVVfeXFMTWFCNFFwMm9ieEpEVldtYm5qQmZld19VYnhYZFkwdnAybkFXNWdOalJndzkyMjJGWGszUXJqWnltNXFMWDNHeHZVbzZCbGJ1YnZ5T2hmTGZyaFlJWmpiY0R2bmpGakxyM0VqSVdfVnp4VTh2UVVZTjJQV2NZbXNLT0RfX1dYZXQ5dGNqdEtibV9KZmdISVI3dzlrdGcwMHlwNkVZUkl1YkRtN1BBU3UxSk1UNG1RMXpUZzdLampNZE93S0NBZHhKa0syakF0?oc=5",
    external: true,
  },
  {
    id: "cockroach-janta-party-top-indian-judge-s-comment-sparks-sati",
    date: "2026-05-21",
    source: "Al Jazeera",
    sourceType: 'press',
    title: "‘Cockroach Janta Party’: Top Indian judge’s comment sparks satire, protest - Al Jazeera",
    blurb: "Read the full story on Al Jazeera.",
    url: "https://news.google.com/rss/articles/CBMitgFBVV95cUxNX2RUTnJQY2dKaFp0bmc1Yy1NcDMxTWZwcjFWV0FHZmVDcXQ1dUEwcGJpTlE5U25Td0k4cWFHTGotQTgtVmtNZG13NFVIX3F5VE5GYURKX3U5b1czRGgyc29kajBLM2FCTzZlOHVLOElRVzJOMXB6ZmZJQTFPcUVXd0VfNlBZa2JJY1dVblNHLV9jb3BNTWZrNnhoN05Vb0psVWN1TS1CbUZIOGVEUmdKX192d2J3Z9IBuwFBVV95cUxPY25Xd1FGYXpiVC16YVBzNmVCMkdCUFFIdjlIVVFCTDJrSWMxdmhpSEdSakFrT1RKZjR5SkdaWFpoLXZrRDBIY3A4c0VyTkNORm1tQzFyVHZFemhHSTFtN3B5SjZfVDlwaXNqWFRaS0FRdWNXb0g2RHBrZVBrX0xnUE5VelRIYnlTU2kzTDdodWpxZkxfdW1vbkwtMWM4Vll6UEZicUMxS3d4UmlGU2M1YkJsVG9sQjB2dmFV?oc=5",
    external: true,
  },
  {
    id: "cockroach-janta-party-social-media-frenzy-or-just-hype-ndtv",
    date: "2026-05-21",
    source: "NDTV",
    sourceType: 'press',
    title: "'Cockroach Janta Party': Social Media Frenzy Or Just Hype? - NDTV",
    blurb: "Read the full story on NDTV.",
    url: "https://news.google.com/rss/articles/CBMimwFBVV95cUxOVG8zdkhONWlLVU5UQlZ3cU1XbVlEZXM0cDd0aHFKTVl3cTQyVnBvTXh6SEhsa3pfYXJpYXV2dVhmRW42bGdVaF9JTnVrSXlROXZIUm4tZUk1R1ItbUJGeGNFbE05cTdwd2w4eFRieTM0WndCbXR6R0NJVm5uX2lKZHY3c1FtY1J2TDdlbUctOVV1U3g1WVlzZ1daTdIBowFBVV95cUxNZG9Gc19ZanlRaU9sNnZoRkNWSXl2MXRDVURmR2c1cE5Jd0pzcy1XUlVkUEZBMmpXYURTdEY5ZXJxM210YjNzakk0OVZ1T1RIdVdrREhXWHZSUHRtcVRzV0tDMVpFWFFGam1yVlN6UmtCOHRNVXFMMGl0cEU2a3B3dkd0TU9rNExnM3RjMlYyVjZhQjNUZDh0UXBVak5USG40RUFz?oc=5",
    external: true,
  },
  {
    id: "why-a-viral-cockroach-protest-party-is-growing-among-india-s",
    date: "2026-05-20",
    source: "Forbes",
    sourceType: 'press',
    title: "Why A Viral ‘Cockroach' Protest Party Is Growing Among India’s Youth - Forbes",
    blurb: "Read the full story on Forbes.",
    url: "https://news.google.com/rss/articles/CBMiyAFBVV95cUxOQlBIRVd1OC1HY0oyNDBYVDJtZTIwWG5JN21RcGYyY3k5V0s0WHp2WGZIYVZxcUwyRnhqV3NkdVdzMEc0SmlCbHo2TUVjZThha2V4bmNPMG5GdG5BU2ljMVU2Y1pPQlNjNXkzUkRTMWpyXzBFeWJMaVMweW5jdzFiS1lWNUphN0ZXQlJmdEx5MlZ4QTRTT3I3SEVOX2l0Znp3X3N5RzExZ2R4ajhJMVNFU2xwRVhLb0VVenhtczMtS3VIWTZMY1dRVQ?oc=5",
    external: true,
  },
  {
    id: "two-trademark-applications-filed-for-cockroach-janata-party-",
    date: "2026-05-21",
    source: "Live Law",
    sourceType: 'press',
    title: "Two Trademark Applications Filed For 'Cockroach Janata Party' - Live Law",
    blurb: "Read the full story on Live Law.",
    url: "https://news.google.com/rss/articles/CBMipAFBVV95cUxOS01BM2xrQ2o3X2xuUVZBSzF4c0QyZ2MtRHlkTk5yc0h6QmpISmJDdHhCOEFLRDlvbzlZU21TSllKa3oxN0dBbzlBZ010NjRoc2tLZkw0LTlGeG5BdndJRjZtLTVJV1A0YkJhZGJKaXNQZUttRHFSV1REUmZaRmVfa1RIWHp5T3hreEoyQXVQVUlCZmZETmR4UVlnOWpVMnNkTVFBc9IBqgFBVV95cUxOWTk4eVZKLUtjcnlNTF80OXVhRHhFNlZLMFZuQzladlhoMTQ0MmswTmtQTDVPWkwzeUhRWGExSmN0bjA5ZTRBUmJsRXU4RnhOZUhsbUR0OHI2cWVCOVU2Ym0wMU9VX09lRkwwdlFteTV4bDItS3RfUUxLWDdhbVQ2d1RLTlg1a3pBRHNrdG5FMnVWRHdhMGxNR0FtdHZ3VzRPTTVVbjJUS3pFUQ?oc=5",
    external: true,
  },
    {
    id: "shashi-tharoor-s-advice-to-opposition-amid-cockroach-janata-",
    date: "2026-05-22",
    source: "NDTV",
    sourceType: 'press',
    title: "Shashi Tharoor's Advice To Opposition Amid 'Cockroach Janata Party' Rage - NDTV",
    blurb: "Read the full story on NDTV.",
    url: "https://news.google.com/rss/articles/CBMirwFBVV95cUxQR003MnBFcFV1bU52aGZ0dmlzd0pXZi1ibW5ONHE0ekpORVpsUThZcHpQbW5xQkMtQ0tjcUptYjc1b1ltMkpQaXZ3WC16LUVMQUkwSkd4cGhKeEFfUjdWS0ZFRGZsUWJoQVBVWXZYS2FLclpiT3lwdTBLTlRZMURKV1RWbkFFREU1eUE0VnF1dlFYaDBER2RyN09wY2ZlM2dTMTBNWXVaOGN4RkF2N3U40gG3AUFVX3lxTFBHRVhndk04cW1xODhDUDNPbGVjbnZHY1U2dzVlMkl1cHozWElBUml5NUQyVmVRSjFDVDNybmIxc2thYmJXSEdWeW1lMzhKMldkTDItUUkta056VzFfcTdkVjY2VXFaeUEyVTgxWHJPSHpGdTVIRW5nUFpkT2tJRWVJQjQ0dlZMOS1nOHBndDZPdTZoRjNYbllNa283Nk1YOVlqYlFoYnRHbHR1dG5HdG9wTG9WVjNRRQ?oc=5",
    external: true,
  },
  {
    id: "founder-s-parents-lose-sleep-as-cockroach-sets-social-media-",
    date: "2026-05-22",
    source: "The Hindu",
    sourceType: 'press',
    title: "Founder’s parents lose sleep as ‘Cockroach’ sets social media on fire - The Hindu",
    blurb: "Read the full story on The Hindu.",
    url: "https://news.google.com/rss/articles/CBMiwwFBVV95cUxPbm9QYWtkTXd3ZFlCUS1oRExIdHdYMmFHVzRpTUpZMHpnWHRQRTVRUFNRUU1hY3ZrN1dwVnRpVm05XzM3QnY0NjkzZHlOQUwxbDZCZXB4ZG9sbGE4YmtqbVJvMDluZTR3TXdadjRCUTgwQmROWTgxQ29CUUhwZHhtSmlqVUs1amFWeTVlVnJTYklEeWRBV2RaOGlQb2ZSNk93bG9WZmJVNTEyOWg1cWxKclRaUW14Y2pIbm1PVFJPVDdOMHPSAcoBQVVfeXFMTzJ6NzNVcklVQ190MlRQcEQ0YUZSNlpuMi1kQWk0VEFuTjQxcms0UE0wRHhzbnFkaHhGeFVCZnZQc3NMRWh2dGtQMDFuSVAySTBlWFZTTkhpSkhTM19nbV9vaDU0d1RNcG1iWWFuVzRVczJVODVIZDdUa0pJcnhtdTdGeVV3bW9RMjZlYUlrMUkyaW1FREZuYktFQXdPME1lTG9MVmxnWDdsXzFaVVFIVVpBbFlMc2U0aE5uUHk2RHFvOVY4UDdxWkZHQQ?oc=5",
    external: true,
  },
  {
    id: "we-do-not-want-him-in-politics-parents-of-cockroach-janata-p",
    date: "2026-05-22",
    source: "The Times of India",
    sourceType: 'press',
    title: "'We do not want him in politics': Parents of Cockroach Janata Party founder Abhijeet Dipke fear arrest - The Times of India",
    blurb: "Read the full story on The Times of India.",
    url: "https://news.google.com/rss/articles/CBMi-wFBVV95cUxNTFFIeDZ5cWVwQXktNzVaY0Y4X3A2SUgwQnVRQjdEMmFhcDJaOFVNN0x2LTNFQVdVVUxkM0p2TDV0enhKT3ZhR0k3ak9fSUZvMG9IRzEzeVM3Z0prSl83TERaTjRBOWJYdUpiUngxci13dm9QLWo2UEJpYWFOT1pLS0dIY3dORTIySk13M20wREZfRDhKSExYekVtemFOM3FOS2ZHZHFTMVh3LTU4dmktdk5hT1h5Zm1XUUJtOGRKX2ZjZzFxeWE0UDBIOXkyVk9mQ1hLZmRJamtnMWxrT3pldWFIbVF6TlZjSWhyYkFWZjlzX012SWRwUzh4UdIBgAJBVV95cUxNRkRpcTJ1WVhfaUhiQVdDbUhxZzB6Z1p6b01ldFFOTkI5U0Y2akZHYVVqUTdfWmdJbzQtX0hmNU90OWtSM3NvSlNldmtpeEVnTzJGLUJYd1NHTGpOQVFsN09XZXlVRG1SZjdJUGdmWXF0ZGRqNDlnQmRFaTRWZDJ0UEJaVVlqYl9qNUdEcG45X0tqNFVJaGRZRGJBbVI5ZGd0TFdmNXF2UExjcW1TNUQ0cWlwMFlSdHk0dnhBM2FhN3pzQktnUDI5SUg5UkxlbkZlenBwX0s5emF4NDFkYjFzRWdnMjdsTzRlMlBPUVdiOVN4V2JVWlhXblBZM2tLVkZD?oc=5",
    external: true,
  },
  {
    id: "who-is-abhijeet-dipke-founder-of-online-sensation-cockroach-",
    date: "2026-05-22",
    source: "NDTV",
    sourceType: 'press',
    title: "Who Is Abhijeet Dipke, Founder Of Online Sensation Cockroach Janta Party - NDTV",
    blurb: "Read the full story on NDTV.",
    url: "https://news.google.com/rss/articles/CBMizwFBVV95cUxNMmNZa0h3MzBOTEF5Q19ZUTZxem9aQmlZbXJRWXNUVWEwSXJyb00zZ0F4LXJud1BDNno2U05FcnpxVVZEVVJvUWpiMk42emo1UThIS1Jib0pwMW43VElNdzBFR3hxODZhaXJYb1B1UG5IeGtGekNqTnJLM2JQRTNNWWF5UVdRX2VHbnowdWhRM052WVFZMFhIMTNPNklTS2hYSFgzMzhPMmw4X3hjRHliWlhmai1zazNiYVk0S1p2UDlweWhJUFBadjNOOV95MmPSAdcBQVVfeXFMT1VnMXJYTU42RXpOSzlyWEJ4emIzdVBoYmlxd1N1eDZlcXZSTnFFVkdyMEwzcjBRMXJZX0RJeVZreW5PcUJDWk9iUzZMb0lEeWlBTWs1ZXJpRmR3Q2QxTzdGbGlncEo1QVFscGFuZkh1V2pDUVY0NWdLbU8ybVFBcFA1aE1EXzFGaEx2SlFYbHdWMGdNMUJSMXdIY1Nwdkg0SDdDTmpCUWdrWFRvalVkc09vV1JGMi1TTkF4VVcwMmZ3cGoyZktySl81ZmFoZ2xwa1Fnbk1QNWM?oc=5",
    external: true,
  },
  {
    id: "parody-cockroach-janta-political-party-s-rise-reflects-youth",
    date: "2026-05-21",
    source: "The Guardian",
    sourceType: 'press',
    title: "Parody Cockroach Janta political party’s rise reflects youth anger in India - The Guardian",
    blurb: "Read the full story on The Guardian.",
    url: "https://news.google.com/rss/articles/CBMiqAFBVV95cUxOOFNNWDVZbnNSTExVYUNYdkpZYTFrV2xWT2dZdTQyMFNhSlgxMm1ZZ2FYcFN1SG0zbTZPWG9xUVljUDAwU2QxLXlkQmZfVElSTFl5SHNzTnVsQ1dZd0U0M1lrZG5RTl9wVlpwRWhKWHlmOTVEMjBNSlNfSmJsNEtoNEpTdlR3b1FCNXBETWR1VXZocU52bmpuOTRfTWlIVU9zc1pKbkt3ekc?oc=5",
    external: true,
  },
  {
    id: "cockroach-janta-party-dalit-founder-abhijeet-dipke-faces-cas",
    date: "2026-05-21",
    source: "ThePrint",
    sourceType: 'press',
    title: "Cockroach Janta Party Dalit founder Abhijeet Dipke faces caste attacks on X - ThePrint",
    blurb: "Read the full story on ThePrint.",
    url: "https://news.google.com/rss/articles/CBMimAFBVV95cUxQeF81Y1dZLXdlMFBoTDBoSjk4b21PdktBQ3lMXzBYX0NWNFZibFpDZWRadGVGWWFaUXc2enlJMkFFY1NSczRfMTlhLWpuRk55NmRFVFVRbU1TZHVXOUJ6R2RDNThUTDRZWGw1QUFVYWVWcG5VWWNKaUhHX24tSGtJVV9mOEJsSWduVHBPcTBMTmtMRFd0dVM1WtIBngFBVV95cUxQcS1SV0pUbHAweGxPSG53X01kOXJqZE90anRRc3g4T0hxT0ljS0RjUUs1YV94VmdoVDdYZG5qbDJyR2YzU1ZNWUtHTXozWWROOF9oNHZEN0VPbmxlZk9ES3JYNS1nU1VDbWJhREtiZldwNVlORG4zM3ZJa1ZOVTRCSTlhZzZtSUVoN1dMbWlVcUl4RGZIR09COVItajVTQQ?oc=5",
    external: true,
  },
  {
    id: "cockroach-janta-party-has-nearly-80-followers-from-pakistan-",
    date: "2026-05-22",
    source: "The Economic Times",
    sourceType: 'press',
    title: "Cockroach Janta Party has nearly 80% followers from Pakistan, Bangladesh and Turkey, claim netizens; poten - The Economic Times",
    blurb: "Read the full story on The Economic Times.",
    url: "https://news.google.com/rss/articles/CBMipwJBVV95cUxQZDJKUkIwWlY1VEpwdnhQSF9oTXVDLVFqd05oYnowWC00ZldMRjEtcjdkSjBkcFZOUkYxWnNMM1psbUhZVHQ2STl1MVB6MC1qZkRla1Z3dUZWTXliYXV1TG1VV0lmY1BDQk5jdTdiRW9yWlh3SmpLaGo2cWRfSHdpc29yTXBiSXU3NmYxZFdOOWY4QjNRakg5Y081Uk50aVZaaGRvTE5hZWV1dEh6V3g3Y1RiUU9Udzh1NjE4a1JlMmQ5a21MTHdWTWZMWGJoaXdCbmlYNlhQcS11R2J5MEU0MWU5Ulhib1gyMTc0eGlZc2pBcndjcVFUcWtRVzhYN1hGRUhLeE5UeGtwNUtDVlI1Zjd4dUVOdkNNSkVMYXpSSlBIWVV1Nk1J0gGsAkFVX3lxTE1Pa0NJUjE1RXgzaklnS1oxY3BENVNZM1k1ZFFINjBBeFlfSEpYZlc1LVBqWnNDZXNiOVVheVBzOFdWTVNNb29VMFV4WVA5aGJYSlI5OWN2c1BCbUtDNHl0LUd6WVJxanRVNHRUQkxyamRNbElBMFp5dS1IMHhORTY2X3VFS2NQakVGSkcyN1ZRdW10NWE5WklBWi1vb2t1MVN0SmJkTnlQVHhrckMzN3I4NW03ZDQxNUZ2dDV6d2RvSG01YWhBdVdUQzFwZUZLdG02UUxlQm1PbUJ1TnZ0S2VoVHppWXcxbkpzUnJFTDFjWmp3TFBnM296alFwci04RE1TMkVwNlFlaVBEOUR0a2w2TjRwZ0J0UjkzRUZuSmF5LTRycGpTdUs1TXRtRQ?oc=5",
    external: true,
  },
  {
    id: "in-cockroach-janta-party-handle-government-sees-national-sec",
    date: "2026-05-22",
    source: "The Indian Express",
    sourceType: 'press',
    title: "In ‘Cockroach Janta Party’ handle, Government sees national security threat, asks X to block - The Indian Express",
    blurb: "Read the full story on The Indian Express.",
    url: "https://news.google.com/rss/articles/CBMi5AFBVV95cUxOYVhPelF5UjJ4M01jWVRZVHRTOFlvaU1Ld3BjaGNmaVNRZXRXVWFpVmtyLVVfVTB3U3VGMmlmN3ZuV245M2FRT1oyeUhfNU56VTc2ZUJWMm01QkM5N1l3ZWZsdVdublV4YXVUYkptbHo2QmVCQWhLZTQzZkFWOEhNRUE4RE5FdjlCS2h2OFVXYU9rQzB3TkxEOE1KUkp2VUxaYnlFUWZuRmFiWk1RSHFHWDQzbWtEU1JXVS1mZE92bnkxSTlCOHZwWjJkTGhlQWtCOEN4ZGRXZjNLZlpfMUFZbHhPalfSAesBQVVfeXFMTWZsai0zcW1vc21aQlJQckp1cTdmcG4yM0FINjI0Ty02VHdSWEJTZ1dhWU5mTTI4OWFlUjhJRlgxUHlCdnBlVUloSWw1dDlzeFJ0QUFlU2NwdjcxNTYtbFRwbVZjR2dpNWg3YXpkZ2ItVE9NcF9jZVdtc2RGcGxTakp4ZUIwYWxTNDlweXl4ZXF4Q3ZDcXltYll2M2p1cVkzTFhqZ1Z3ellQaWdEQjN5MXlZNklyQUpXdWpwTHhRRDNIRWh1bmNYYWVuc045bWoza2gyRTc1YXhZa08wRkFBYjFaQm9WaWhqY1Vhbw?oc=5",
    external: true,
  },
    {
    id: "india-swats-cockroach-movement-over-national-security-dw-com",
    date: "2026-05-22",
    source: "DW.com",
    sourceType: 'press',
    title: "India swats cockroach movement over 'national security' - DW.com",
    blurb: "Read the full story on DW.com.",
    url: "https://news.google.com/rss/articles/CBMikwFBVV95cUxOZzBhSndZWnItOEhvM0t2aE5Jc1ptR1h5ZkhMdEdBakpibXpVZ245a3A2VTBGM2lKSVRkUkJrUElWMGFjaHVJWkc2Nkkxd2luSlJZZWFxWDBuU3R5WVVSSE9lX29TZWpISkU2NkY1V1dueF9VOE02YzROdm9NSU5TazFzbk9GNkdVRHVlQkxHQXNoRzA?oc=5",
    external: true,
  },
  {
    id: "marwa-denge-tujhe-cockroach-janta-party-founder-abhijeet-dip",
    date: "2026-05-22",
    source: "The Times of India",
    sourceType: 'press',
    title: "'Marwa denge tujhe': Cockroach Janta Party founder Abhijeet Dipke receives death threats on Whatsapp - The Times of India",
    blurb: "Read the full story on The Times of India.",
    url: "https://news.google.com/rss/articles/CBMi-gFBVV95cUxOOVBROHZfMmR2TnM0RDdRd184RXEySnp5RkhWQ2x3Mi1ZTmVveGE2WjdKUFJodDRxNXFNcUptenNnNlY5Q2JoWFZITjY0Y0JTR0ZsNWR2RUkxRmxLSTlqMjMxLW5xUmxaTXgtRjBqN2NoMDg2TmVlOU5vTzdOc25LQkVGb2ZjUElnQUp0aFVQRkMtRzViUVlJVFZWTG52SGdINWw2SURvMFhMTWlUSmZ6ZEx4U3NBdFlRb1IyaGtJVGxuZjZmYTU3aHRQOWZBTVVlUmdKM2JXQWw2akt4YV9NODBTLWNhMU9KN2NmYUVxRXJFZlBUdUhERWtB0gH_AUFVX3lxTFBvRFJXMk1WeDMxQnZfUnBNVTBwRVhoWUNJSjE2NlcwcUhTckZRbVk0RkFOV0pHWkVKcjNKRlI3NmxsMXEyS0dZeklzSmQ4aWJoUEtxOVVxVFRmM2JSSHpWYlJfMUcyN0NDaXY5d1Jsa2pSVFVrc0xKNzBnMFhVZVVpMHRmS2VHT1hlU2p2RjdXX2hzalByZVFZcURCbGlMTTBRbzFXTE9XUllCZ3JEY1ozVGZnNDR2cWkwTU4wNzZ1MFYzV0J2c0Niam4tUEpYLXdJYVk1RUhFOTU3Rm44UlBDVVBEUi1tUktTRmRpZ0lEMlJJZVFnZjNxM1oySEc2aw?oc=5",
    external: true,
  },
  {
    id: "cockroach-party-makes-neet-leak-its-first-major-issue-target",
    date: "2026-05-22",
    source: "India Today",
    sourceType: 'press',
    title: "Cockroach Party makes NEET leak its first major issue, targets Dharmendra Pradhan - India Today",
    blurb: "Read the full story on India Today.",
    url: "https://news.google.com/rss/articles/CBMi_wFBVV95cUxNbVN1LUw5MG03ZER6T0JyN0RBS09EZE5JUzlhMjlPYzU3QzR4MTkwZUxLQlM3aFRLRzdVSEhPYk1LUlo3aFhkeG1hOFpDZzJyRE5jRDdxSy14R3hEUVZvVXIza01jSHFVM2ZoWlJDMkRWMXE3aGVXcDF0WjQzeV80X1Z0MVJ0WVlYS0phQlphMFRQbzJZRjRoaXlDNnZ3UUlTUERZVTdvOEFYQjFOYmNocUNUMGpWSk5ZV2N1aGplX3gwblRSS3A0WDVDSmxYZ3R4YzMyYno1Z2RqTEpLZkhaYnlpZllpUmY5OTl0VHV6b1A2NS05c1RjNlBQQk8tLWPSAYQCQVVfeXFMT1hQMDIzamdyazU0bG54aHhGdVVTVWlsdXpKTTI4d2dMLWRmUEY4VE1KWTBoUWNnbDgyOGQ3WEl6Tk1vb042blR3SFNIYWxpc0ZET2d0dzQ5aHdmaTFSYzRRYzU2aTlZeTR0ZXZ3bTBMQ0xXTXlRMG4wUVRVRUR2YTFZc0JxM01vd1BQem9SUzd2Um5McGlUYTVjZXlRSFFhNmdIR2tlaDFnZER0dkF4QzhUR3VoYm5RWjlqaVhBcVptSmcyWlhsMTA4MkxXUHRVdDNHbm5UTExFRjVDa2VoTjRFUkY4UzdacmVXUHhJMXM1N19EaWYtOHUzMjdmMWRiTC1GZko?oc=5",
    external: true,
  },
  {
    id: "india-s-gen-z-have-flipped-the-lowly-cockroach-into-a-symbol",
    date: "2026-05-22",
    source: "CNN",
    sourceType: 'press',
    title: "India’s Gen Z have flipped the lowly cockroach into a symbol of defiance - CNN",
    blurb: "Read the full story on CNN.",
    url: "https://news.google.com/rss/articles/CBMihgFBVV95cUxOcUQ1T2hucjFETVRkSjBta2RhN29UNUR3TzlOTS1zanBHTEVvVnEtbkpkSVA0SlE3Zmtocm1WNFJKTG4tTUJoWk5JM3NKaFhBcmNUSUVrSmJvTloxdlN6bmphUUEtOFR1cHpHcGlFbnJLNHZFN2hxVGMyd0p2QnNPbXVRdXpHUQ?oc=5",
    external: true,
  },
  {
    id: "shashi-tharoor-slams-x-ban-on-cockroach-janata-party-the-hin",
    date: "2026-05-22",
    source: "The Hindu",
    sourceType: 'press',
    title: "Shashi Tharoor slams X ban on ‘Cockroach Janata Party’ - The Hindu",
    blurb: "Read the full story on The Hindu.",
    url: "https://news.google.com/rss/articles/CBMi4gFBVV95cUxPSEpYRWNGV0hDVXF3TVBacW1ib3A2OGVxTHEyVlB4UDZkdFFZYlFsYjdGWjBTTng1NUlsdUMxMDhyMDZESWhPSkZkX0NHR1RjYVJQWHZGOVowV29FYWdCUG0xNjUzY3BXNElvNDhIaU85amxkbG40bG00ZkRJS1otZjFvMXRtS3BpeUJQem5BMXJzaWxJYXA0LVNKZnQ0WmxNeE5ySFpLWU9zS3AyNmhfUjNKTEhFckxJX1JIU1dLdU9odFBGQlRiWXVodF93VnB3bU9MMnN3RUpGOC1SQ05tc3l30gHoAUFVX3lxTE0xU3lqLVVoSXlVMnhueHZiSnFDcWxuTU5HZmVCd3hoYk5CRXdoUVBERlUybERKRl95ZXlXS3JOR2M5Y1RuWFNyR2JaNU5GZ19TMmlLWnNzSW5MZmpKSDVLLU5DTTJPOXl5OHljc1FRQVZYT2g2ZVlCUjNFUGVkUVZoY2R4b24tTy1jeUh1MTR4SFBjb1lnSWJwdXliT0s3NnBZYUdiR2RXbXh1ZzhxMVZmRlZUbEkzM1BxQl9uUTZlMnpPaG9UQzJYTDgtM2hvWTN2UUFVRkkzZ1ZuZVJxaHdZaTktZ1ozeFo?oc=5",
    external: true,
  },
  {
    id: "now-a-pakistan-and-isi-asset-claim-against-cockroach-janta-p",
    date: "2026-05-22",
    source: "India Today",
    sourceType: 'press',
    title: "Now, a Pakistan and ISI-asset claim against Cockroach Janta Party, its founder - India Today",
    blurb: "Read the full story on India Today.",
    url: "https://news.google.com/rss/articles/CBMizAFBVV95cUxQT1dLUTZMaVRzU1QwcldOSkxxekRxa0lQc2tRTmxrTUx2dmQ4OVVBalRvYnN4d1NzamFCeTZyeDV0Y3BzNDREa21sTkJ0NVNDQWxBTE93dVhqNGltNHFsMUUzUEYxaHRoTUcwX3htTl9VVkFMM1o1RnRCVWRhSDJjZUhydEdEWlQ3Y1pXQ3UtZUVFcXFJS0tjSFRqS1VEcTNqWk1haG5ZOU1iN3FfR09iZmNrNlFPLWhuQ3ZnS1hQbDYyS01hVmVWbi1wbjfSAdIBQVVfeXFMT1MyQ3poc1NDem5lZW1ZaHlWU1EzOE5hbGV5MVlEM3BZWTA2cWJ6aXlXUEs3WjM5MGRVT1BEODZjUVBsNlJYekpZWk1MSTRtS3Y0VVFoREhhcHN0RlFyM1A5WE9hM0NYcjRyUkRoZE5qTTFQLVhJckNPa052UHEwSUp6R01BWlRkVWpNcGhpalFxanc2T0dNNkxpempVV1pKRURiYlQtQXIwVE1kQmtTVkNkT1RBVUFjOGxGYTVtZ015MmkzMFBhVTNfd01CMnlIbWJ3?oc=5",
    external: true,
  },
  {
    id: "what-we-know-about-oggy-janata-party-group-questioning-cockr",
    date: "2026-05-22",
    source: "News18",
    sourceType: 'press',
    title: "What We Know About Oggy Janata Party, Group Questioning Cockroach Janta Party's Political Links - News18",
    blurb: "Read the full story on News18.",
    url: "https://news.google.com/rss/articles/CBMi2AFBVV95cUxQcV9yaGxyRUhtaV9tNUZaNDdhLVpzUndFOXVFRzVJT0VOZ2Q1YTVGS0VjWVBqSlVEZ3FUMmJybFpwdkk5bXNoM25heUlCWDdNWldzMS1UdFdQQUVfSWlZT2JHamJKU1JYUFJLUW1ZVUdrUGFvbTBFaExGdF85bjlGM2ZXYzdfalFyVVIxblpnUXFqSS12U0dQREx1YmYtMHdlSlpjNnM1cTRHTmJOallFckdhSlFFRGFOQVJoaUl4REFKZHg5Q2lRY0VoLVBDZFlyNTJWdUdIb3TSAd4BQVVfeXFMTXhkamg5SmdCVnBGUjc4VVZ2dVJfSXByc2ZnVmR4UXVLTzMtTlFDMlB2LVFheG5sbk1ETk5iRUJfLVE2Y29LVVdxTVplbWFCSFBEb1gxekpMa0o3eVhRZUdUcHFadEM1QXZoOVJZekFPX1pySjNIMWw2UmoxQWU1Rkc0aXBkMldLd29scW1pTVVNWHZsX1l6ZVI2aHQ2RkN5bm5weUZoNTNSUmNyZGRtYTlTaFNwYTIxNldGTFUxMll1amdjb0N0enFSWExCMzlqd3d2bmZQTnRtYWtQTjdB?oc=5",
    external: true,
  },
  {
    id: "written-off-as-parasites-young-indians-back-a-cockroach-in-p",
    date: "2026-05-22",
    source: "Australian Broadcasting Corporation",
    sourceType: 'press',
    title: "Written off as 'parasites', young Indians back a cockroach in politics - Australian Broadcasting Corporation",
    blurb: "Read the full story on Australian Broadcasting Corporation.",
    url: "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNc29XSUJVaTNjME5tT3R5ZVBKeTFodkFGRHhaVkhQcFprZUdxNjlQZHJHM1otcFl1UzB1WHUtazhPajYwRWRyVm1aUFh4b3pYRkpaNDVZZm9hYmlhdFZZcWNYV3MwVVlxcUt2cmpvT2M5NVBlbjZWOGlXekFSX1lKUmg2QmpkNEdPNHJTVGp2Y0ZrV1BMeE1kM3Y1QW1wUG1XTlRubDI2Y3pKZw?oc=5",
    external: true,
  },
  // AUTO_NEWS_BELOW — the bot appends new items here. Do not remove this marker.
];
