export type TeeDesign = {
  slug: string;
  name: string;
  subtitle: string;
  description: string;
  price: number; // in INR
  tagline: string;
  colors: { name: string; hex: string; label: string }[];
  designType: 'badge' | 'manifesto' | 'logo' | 'card' | 'thesis' | 'wordplay' | 'solidarity' | 'campaign' | 'report' | 'podium' | 'shades' | 'tricolor' | 'inchief' | 'inflation' | 'wifi' | 'censor' | 'pothole' | 'powercut';
  category?: 'tee' | 'mug';
  featured?: boolean;
  personalizable?: boolean;
};

export const COLORS = {
  red: { name: 'red', hex: '#C8331C', label: 'Election Red' },
  black: { name: 'black', hex: '#1A1714', label: 'Charcoal' },
  white: { name: 'white', hex: '#F5F1E8', label: 'Off-White' },
  beige: { name: 'beige', hex: '#D9C9A5', label: 'Khadi Beige' },
  olive: { name: 'olive', hex: '#5C6B3F', label: 'Olive Drab' },
  cream: { name: 'cream', hex: '#EFE6D2', label: 'Khadi Cream' },
};

// Standard 5-color palette every tee carries
const STANDARD_COLORS = [COLORS.red, COLORS.black, COLORS.white, COLORS.beige, COLORS.olive];

export const SIZES = ['S', 'M', 'L', 'XL', 'XXL'] as const;
export type Size = typeof SIZES[number];

export const PRODUCTS: TeeDesign[] = [
  {
    slug: 'parasite-of-the-system',
    name: 'Parasite of the System',
    subtitle: 'The Badge',
    description: 'They called us parasites. We made it merch. Worn as a badge of survival.',
    price: 499,
    tagline: 'CERTIFIED. STAMPED. PROUD.',
    colors: STANDARD_COLORS,
    designType: 'badge',
    featured: true,
  },
  {
    slug: 'secular-socialist-democratic-lazy',
    name: 'Secular. Socialist. Democratic. Lazy.',
    subtitle: 'The Manifesto',
    description: 'The official four words. Print them on your chest like a constitutional preamble.',
    price: 499,
    tagline: 'THE PARTY LINE',
    colors: STANDARD_COLORS,
    designType: 'manifesto',
    featured: true,
  },
  {
    slug: 'cjp-official-logo',
    name: 'CJP Official Logo Tee',
    subtitle: 'The Symbol',
    description: 'A cockroach holding a broom. Election symbol energy. Tell them which side you\'re on.',
    price: 499,
    tagline: 'VOTE WITH YOUR CHEST',
    colors: STANDARD_COLORS,
    designType: 'logo',
    featured: true,
  },
  {
    slug: 'unemployed-by-profession',
    name: 'Unemployed by Profession',
    subtitle: 'The Card',
    description: 'Designed like a business card. Add your own name and years of nothing. Hand it out at family functions.',
    price: 549,
    tagline: 'PROFESSIONAL CREDENTIALS',
    colors: STANDARD_COLORS,
    designType: 'card',
    personalizable: true,
  },
  {
    slug: 'apocalypse-no-job',
    name: 'Will Survive the Apocalypse, Still Won\'t Get a Job',
    subtitle: 'The Thesis',
    description: 'The whole movement on one tee. Nuclear-grade resilience meets the Indian job market.',
    price: 499,
    tagline: 'EVOLUTIONARY GUARANTEE',
    colors: STANDARD_COLORS,
    designType: 'thesis',
    featured: true,
  },
  {
    slug: 'roach-before-rozgar',
    name: 'Roach Before Rozgar',
    subtitle: 'The Hinglish',
    description: 'Roach before rozgar (employment). The new desi motto.',
    price: 499,
    tagline: 'PRIORITIES, SET.',
    colors: STANDARD_COLORS,
    designType: 'wordplay',
  },
  {
    slug: 'main-bhi-cockroach',
    name: 'Main Bhi Cockroach',
    subtitle: 'The Solidarity',
    description: '"I am also a cockroach." Devanagari + English. Worn in protest.',
    price: 499,
    tagline: 'मैं भी कॉकरोच',
    colors: STANDARD_COLORS,
    designType: 'solidarity',
  },
  {
    slug: 'vote-for-the-lazy',
    name: 'Vote for the Lazy',
    subtitle: 'The Campaign',
    description: 'Vintage Indian election poster meets Gen Z apathy. A poster on your torso.',
    price: 499,
    tagline: 'CAMPAIGN HQ APPROVED',
    colors: STANDARD_COLORS,
    designType: 'campaign',
  },
  {
    slug: 'annual-report-survived',
    name: 'Annual Report: Survived',
    subtitle: 'The Document',
    description: 'A mock government annual report cover. Only KPI: still here.',
    price: 499,
    tagline: 'F.Y. 2025—26',
    colors: STANDARD_COLORS,
    designType: 'report',
  },
  {
    slug: 'address-to-the-nation',
    name: 'Address to the Nation',
    subtitle: 'The Podium',
    description: 'A cockroach in shades, speaking at a podium. Presidential. Unstoppable.',
    price: 549,
    tagline: 'MY FELLOW COCKROACHES',
    colors: STANDARD_COLORS,
    designType: 'podium',
    featured: true,
  },
  {
    slug: 'cool-under-fire',
    name: 'Cool Under Fire',
    subtitle: 'The Shades',
    description: 'A cockroach with attitude. Sunglasses on. Apocalypse pending.',
    price: 499,
    tagline: 'NEVER NOT CHILL',
    colors: STANDARD_COLORS,
    designType: 'shades',
  },
  {
    slug: 'tricolor-roach',
    name: 'The Tricolor Roach',
    subtitle: 'The Flag',
    description: 'Saffron, white, green — and one cockroach. The national colours, reclaimed.',
    price: 549,
    tagline: 'SECULAR · SOCIALIST · LAZY',
    colors: STANDARD_COLORS,
    designType: 'tricolor',
    featured: true,
  },
  {
    slug: 'cockroach-in-chief',
    name: 'Cockroach in Chief',
    subtitle: 'The Portrait',
    description: 'A solemn presidential-style portrait. Hang it in the office. Or wear it.',
    price: 599,
    tagline: 'EST. 16·MAY·2026',
    colors: STANDARD_COLORS,
    designType: 'inchief',
  },
  {
    slug: 'inflation-survivor',
    name: 'Inflation Survivor',
    subtitle: 'The Receipt',
    description: 'A grocery receipt printed on cotton. The new inflation indicator.',
    price: 499,
    tagline: 'PRICES UP. ROACHES SAME.',
    colors: STANDARD_COLORS,
    designType: 'inflation',
    featured: true,
  },
  {
    slug: 'wifi-greater-than-wages',
    name: 'WiFi > Wages',
    subtitle: 'The Equation',
    description: 'A simple inequality for the modern Indian. Connection matters more than salary.',
    price: 499,
    tagline: 'PRIORITIES OF A GENERATION',
    colors: STANDARD_COLORS,
    designType: 'wifi',
  },
  {
    slug: 'unmute-the-mic',
    name: 'Unmute the Mic',
    subtitle: 'The Protest',
    description: 'A protest tee against silence. Free speech, with terms and conditions.',
    price: 549,
    tagline: 'FREE SPEECH (T&C APPLY)',
    colors: STANDARD_COLORS,
    designType: 'censor',
    featured: true,
  },
  {
    slug: 'pothole-insurance',
    name: 'Pothole Insurance Co.',
    subtitle: 'The Coverage',
    description: 'A mock insurance policy for India\'s deadliest infrastructure feature.',
    price: 499,
    tagline: 'EST. EVERY MONSOON',
    colors: STANDARD_COLORS,
    designType: 'pothole',
  },
  {
    slug: 'power-cut-champion',
    name: 'Power Cut Champion',
    subtitle: 'The Trophy',
    description: 'For everyone who lived through 8-hour power cuts. Survival, certified.',
    price: 499,
    tagline: 'CANDLE-LIT EXPERT',
    colors: STANDARD_COLORS,
    designType: 'powercut',
  },

  /* ============ MUGS ============ */
  {
    slug: 'mug-cockroach-in-chief',
    name: 'Cockroach in Chief Mug',
    subtitle: 'The Daily Brew',
    description: 'Sip your morning chai while the Cockroach in Chief watches over you. Ceramic, 350ml.',
    price: 349,
    tagline: 'SIP. SURVIVE. REPEAT.',
    colors: [COLORS.white, COLORS.black],
    designType: 'inchief',
    category: 'mug',
    featured: true,
  },
  {
    slug: 'mug-secular-socialist-democratic-lazy',
    name: 'Manifesto Mug',
    subtitle: 'The Party Line',
    description: 'Four words. One mug. Drink the manifesto.',
    price: 349,
    tagline: 'SECULAR · SOCIALIST · DEMOCRATIC · LAZY',
    colors: [COLORS.white, COLORS.black],
    designType: 'manifesto',
    category: 'mug',
  },
  {
    slug: 'mug-wifi-greater-than-wages',
    name: 'WiFi > Wages Mug',
    subtitle: 'The Equation',
    description: 'A mug for the unemployed who still pays for fibre. Ceramic, 350ml.',
    price: 349,
    tagline: 'PRIORITIES, SOLVED',
    colors: [COLORS.white, COLORS.black],
    designType: 'wifi',
    category: 'mug',
  },
  {
    slug: 'mug-parasite-of-the-system',
    name: 'Parasite Mug',
    subtitle: 'The Stamp',
    description: 'Worn as a badge. Now drunk as a habit. Ceramic, 350ml.',
    price: 349,
    tagline: 'CERTIFIED · STAMPED · PROUD',
    colors: [COLORS.white, COLORS.black],
    designType: 'badge',
    category: 'mug',
  },
  {
    slug: 'mug-roach-before-rozgar',
    name: 'Roach Before Rozgar Mug',
    subtitle: 'The Hinglish',
    description: 'For the chai before the interview. Ceramic, 350ml.',
    price: 349,
    tagline: 'PRIORITIES, SET',
    colors: [COLORS.white, COLORS.black],
    designType: 'wordplay',
    category: 'mug',
  },
];

export const getProduct = (slug: string) => PRODUCTS.find(p => p.slug === slug);
